name: Deploy Email Sending Cloud Function

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - prod
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  push:
    branches:
      - main
    paths:
      - 'email_sending_cloud_function/**'

env:
  FUNCTION_NAME: email-processor
  REGION: ${{ env.GOOGLE_CLOUD_LOCATION }}
  RUNTIME: python311

jobs:
  deploy:
    name: Deploy Email Cloud Function
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || inputs.environment || 'test' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GOOGLE_CLOUD_PROJECT }}

    - name: Create Pub/Sub topics
      run: |
        echo "📋 Creating Pub/Sub topics..."
        
        # Create email-analysis-requests topic
        echo "Creating email-analysis-requests topic..."
        if gcloud pubsub topics describe email-analysis-requests --project=${{ env.GOOGLE_CLOUD_PROJECT }} &>/dev/null; then
          echo "✅ Topic email-analysis-requests already exists"
        else
          gcloud pubsub topics create email-analysis-requests --project=${{ env.GOOGLE_CLOUD_PROJECT }} || {
            echo "❌ Failed to create email-analysis-requests topic"
            exit 1
          }
          echo "✅ Created topic: email-analysis-requests"
        fi

    - name: Deploy Cloud Function
      run: |
        cd email_sending_cloud_function
        
        echo "🚀 Deploying Email Cloud Function..."
        echo "Function name: ${{ env.FUNCTION_NAME }}"
        echo "Project: ${{ env.GOOGLE_CLOUD_PROJECT }}"
        
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --gen2 \
          --runtime ${{ env.RUNTIME }} \
          --region ${{ env.REGION }} \
          --source . \
          --entry-point process_email_request \
          --trigger-topic email-analysis-requests \
          --memory 512MB \
          --timeout 540s \
          --set-env-vars="GCP_PROJECT=${{ env.GOOGLE_CLOUD_PROJECT }},MAILGUN_API_KEY=${{ secrets.MAILGUN_API_KEY }},MAILGUN_DOMAIN=${{ env.MAILGUN_DOMAIN }}"
