name: Deploy Analysis Trigger Cloud Function

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - prod
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  FUNCTION_NAME: financial-analysis-trigger
  RUNTIME: python311

jobs:
  deploy:
    name: Deploy Cloud Function
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || inputs.environment || 'test' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ vars.GOOGLE_CLOUD_PROJECT }}

    - name: Deploy Cloud Function
      run: |
        cd analysis_trigger_cloud_function
        
        echo "🚀 Deploying Cloud Function..."
        echo "Function name: ${{ env.FUNCTION_NAME }}"
        echo "Project: ${{ env.PROJECT_ID }}"
        
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --gen2 \
          --runtime python311 \
          --region ${{ vars.GOOGLE_CLOUD_LOCATION }} \
          --source . \
          --entry-point content_trigger_function \
          --trigger-http \
          --allow-unauthenticated \
          --memory 512MB \
          --timeout 540s \
          --max-instances 100 \
          --set-env-vars="GCP_PROJECT=${{ vars.GOOGLE_CLOUD_PROJECT }},ALPHAVANTAGE_API_KEY=${{ secrets.ALPHAVANTAGE_API_KEY }},CLOUD_RUN_URL=https://llm-summary-agent-377791692293.us-west1.run.app"
