name: Deploy Cloud Scheduler Jobs

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - prod
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      action:
        required: false
        type: string
        default: 'create-or-update'

jobs:
  deploy-schedulers:
    name: Deploy Cloud Scheduler Jobs
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || inputs.environment || 'test' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ vars.GOOGLE_CLOUD_PROJECT }}

    - name: Create or update financial analysis scheduler jobs
      run: |
        echo "📅 Creating/updating financial analysis scheduler jobs..."
        
        # Define the tickers array (matching your original script)
        TICKERS=("AAPL" "GOOGL" "MSFT" "AMZN" "TSLA" "META" "NFLX" "NVDA" "BRK-A" "V")
        
        # Function URL - adjust based on environment suffix
        FUNCTION_URL="https://${{ vars.GOOGLE_CLOUD_LOCATION }}-${{ vars.GOOGLE_CLOUD_PROJECT }}.cloudfunctions.net/financial-analysis-trigger"
        
        echo "Function URL: $FUNCTION_URL"
        
        # Starting time: 7:00 AM, increment by 5 minutes for each ticker
        BASE_HOUR=7
        BASE_MINUTE=0
        
        for i in "${!TICKERS[@]}"; do
          ticker="${TICKERS[$i]}"
          echo "Processing ticker: $ticker (index: $i)"
          
          # Calculate the schedule time for this ticker (5 minutes apart)
          SCHEDULE_MINUTE=$((BASE_MINUTE + i * 5))
          SCHEDULE_HOUR=$((BASE_HOUR + SCHEDULE_MINUTE / 60))
          SCHEDULE_MINUTE=$((SCHEDULE_MINUTE % 60))
          
          # Format the cron schedule
          CRON_SCHEDULE="$SCHEDULE_MINUTE $SCHEDULE_HOUR * * 1-5"
          
          echo "Ticker $ticker will run at: $SCHEDULE_HOUR:$(printf '%02d' $SCHEDULE_MINUTE) (schedule: $CRON_SCHEDULE)"
          
          # Replace dots with dashes for job names (Cloud Scheduler doesn't allow dots)
          JOB_NAME=$(echo "$ticker" | sed 's/\./-/g')
          FULL_JOB_NAME="daily-financial-analysis-$JOB_NAME"
          
          echo "Creating/updating job: $FULL_JOB_NAME"
          
          # Check if job already exists
          if gcloud scheduler jobs describe "$FULL_JOB_NAME" --location=${{ vars.GOOGLE_CLOUD_LOCATION }} --project=${{ vars.GOOGLE_CLOUD_PROJECT }} &>/dev/null; then
            echo "Job $FULL_JOB_NAME already exists, updating..."
            
            gcloud scheduler jobs update http "$FULL_JOB_NAME" \
              --location=${{ vars.GOOGLE_CLOUD_LOCATION }} \
              --schedule="$CRON_SCHEDULE" \
              --time-zone="Europe/Prague" \
              --uri="$FUNCTION_URL" \
              --http-method=POST \
              --header="Content-Type=application/json" \
              --message-body="{\"ticker\": \"$ticker\"}" \
              --description="Daily financial analysis for $ticker (runs at $SCHEDULE_HOUR:$(printf '%02d' $SCHEDULE_MINUTE))" \
              --attempt-deadline="540s" \
              --project=${{ vars.GOOGLE_CLOUD_PROJECT }} || {
                echo "❌ Failed to update job $FULL_JOB_NAME"
                continue
              }
            
            echo "✅ Updated job: $FULL_JOB_NAME"
          else
            echo "Job $FULL_JOB_NAME does not exist, creating..."
            
            gcloud scheduler jobs create http "$FULL_JOB_NAME" \
              --location=${{ vars.GOOGLE_CLOUD_LOCATION }} \
              --schedule="$CRON_SCHEDULE" \
              --time-zone="Europe/Prague" \
              --uri="$FUNCTION_URL" \
              --http-method=POST \
              --header="Content-Type=application/json" \
              --message-body="{\"ticker\": \"$ticker\"}" \
              --description="Daily financial analysis for $ticker (runs at $SCHEDULE_HOUR:$(printf '%02d' $SCHEDULE_MINUTE))" \
              --attempt-deadline="540s" \
              --project=${{ vars.GOOGLE_CLOUD_PROJECT }} || {
                echo "❌ Failed to create job $FULL_JOB_NAME"
                continue
              }
            
            echo "✅ Created job: $FULL_JOB_NAME"
          fi
        done

    - name: Create or update daily analysis checker job
      run: |
        echo "📅 Creating/updating daily analysis checker job..."

        JOB_NAME="daily-analysis-checker"
        
        # Check if job already exists
        if gcloud scheduler jobs describe "$JOB_NAME" --location=${{ vars.GOOGLE_CLOUD_LOCATION }} --project=${{ vars.GOOGLE_CLOUD_PROJECT }} &>/dev/null; then
          echo "Job $JOB_NAME already exists, updating..."
          
          gcloud scheduler jobs update pubsub "$JOB_NAME" \
            --location=${{ vars.GOOGLE_CLOUD_LOCATION }} \
            --schedule="0 8 * * *" \
            --time-zone="UTC" \
            --topic="daily-checker-trigger" \
            --message-body='{"trigger":"daily-check"}' \
            --description="Triggers daily analysis checker to send emails for new analyses" \
            --project=${{ vars.GOOGLE_CLOUD_PROJECT }} || {
              echo "❌ Failed to update daily checker job"
            }
          
          echo "✅ Updated daily analysis checker job"
        else
          echo "Job $JOB_NAME does not exist, creating..."
          
          gcloud scheduler jobs create pubsub "$JOB_NAME" \
            --location=${{ vars.GOOGLE_CLOUD_LOCATION }} \
            --schedule="0 8 * * *" \
            --time-zone="UTC" \
            --topic="daily-checker-trigger" \
            --message-body='{"trigger":"daily-check"}' \
            --description="Triggers daily analysis checker to send emails for new analyses" \
            --project=${{ vars.GOOGLE_CLOUD_PROJECT }} || {
              echo "❌ Failed to create daily checker job"
            }
          
          echo "✅ Created daily analysis checker job"
        fi

    - name: Create or update global data collector job
      run: |
        echo "📅 Creating/updating global US data collector job..."
        
        JOB_NAME="global-us-data-collector-job"
        
        # Check if job already exists
        if gcloud scheduler jobs describe "$JOB_NAME" --location=${{ vars.GOOGLE_CLOUD_LOCATION }} --project=${{ vars.GOOGLE_CLOUD_PROJECT }} &>/dev/null; then
          echo "Job $JOB_NAME already exists, updating..."
          
          gcloud scheduler jobs update pubsub "$JOB_NAME" \
            --location=${{ vars.GOOGLE_CLOUD_LOCATION }} \
            --schedule="0 0 * * *" \
            --time-zone="UTC" \
            --topic="global-us-data-collector-topic" \
            --message-body='{"trigger":"check"}' \
            --description="Triggers global US data collector to fetch and process data" \
            --project=${{ vars.GOOGLE_CLOUD_PROJECT }} || {
              echo "❌ Failed to update data collector job"
            }
          
          echo "✅ Updated global data collector job"
        else
          echo "Job $JOB_NAME does not exist, creating..."
          
          gcloud scheduler jobs create pubsub "$JOB_NAME" \
            --location=${{ vars.GOOGLE_CLOUD_LOCATION }} \
            --schedule="0 0 * * *" \
            --time-zone="UTC" \
            --topic="global-us-data-collector-topic" \
            --message-body='{"trigger":"check"}' \
            --description="Triggers global US data collector to fetch and process data" \
            --project=${{ vars.GOOGLE_CLOUD_PROJECT }} || {
              echo "❌ Failed to create data collector job"
            }
          
          echo "✅ Created global data collector job"
        fi
