name: Deploy Global US Data Collector

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - prod
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  FUNCTION_NAME: global-us-data-collector
  RUNTIME: python311

jobs:
  deploy:
    name: Deploy Data Collector
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || inputs.environment || 'test' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ vars.GOOGLE_CLOUD_PROJECT }}

    - name: Create Pub/Sub topics
      run: |
        echo "📋 Creating Pub/Sub topics..."
        
        # Create global-us-data-collector-topic
        echo "Creating global-us-data-collector-topic..."
        if gcloud pubsub topics describe global-us-data-collector-topic --project=${{ vars.GOOGLE_CLOUD_PROJECT }} &>/dev/null; then
          echo "✅ Topic global-us-data-collector-topic already exists"
        else
          gcloud pubsub topics create global-us-data-collector-topic --project=${{ vars.GOOGLE_CLOUD_PROJECT }} || {
            echo "❌ Failed to create global-us-data-collector-topic"
            exit 1
          }
          echo "✅ Created topic: global-us-data-collector-topic"
        fi

    - name: Deploy Cloud Function
      run: |
        cd global_us_data_collector
        
        echo "🚀 Deploying Global US Data Collector..."
        echo "Function name: ${{ env.FUNCTION_NAME }}"
        echo "Project: ${{ vars.GOOGLE_CLOUD_PROJECT }}"
        
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --gen2 \
          --runtime ${{ env.RUNTIME }} \
          --region ${{ vars.GOOGLE_CLOUD_LOCATION }} \
          --source . \
          --entry-point refresh_global_us_data \
          --trigger-topic global-us-data-collector-topic \
          --memory 1GiB \
          --timeout 540s \
          --max-instances 1 \
          --set-env-vars="GCP_PROJECT=${{ vars.GOOGLE_CLOUD_PROJECT }},EMAIL_PUBSUB_TOPIC=global-us-data-collector-topic,ALPHAVANTAGE_API_KEY=${{ secrets.ALPHAVANTAGE_API_KEY }}" \
          --no-allow-unauthenticated
