name: Deploy New Analysis Checker

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - prod
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

env:
  FUNCTION_NAME: new-analysis-checker
  RUNTIME: python311

jobs:
  deploy:
    name: Deploy New Analysis Checker
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || inputs.environment || 'test' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ vars.GOOGLE_CLOUD_PROJECT }}

    - name: Create Pub/Sub topics
      run: |
        echo "📋 Creating Pub/Sub topics..."
        
        # Create new-analysis-checker-trigger topic
        echo "Creating new-analysis-checker-trigger topic..."
        if gcloud pubsub topics describe new-analysis-checker-trigger --project=${{ vars.GOOGLE_CLOUD_PROJECT }} &>/dev/null; then
          echo "✅ Topic new-analysis-checker-trigger already exists"
        else
          gcloud pubsub topics create new-analysis-checker-trigger --project=${{ vars.GOOGLE_CLOUD_PROJECT }} || {
            echo "❌ Failed to create new-analysis-checker-trigger topic"
            exit 1
          }
          echo "✅ Created topic: new-analysis-checker-trigger"
        fi

    - name: Deploy Cloud Function
      run: |
        cd new_analysis_checker
        
        echo "🚀 Deploying New Analysis Checker..."
        echo "Function name: ${{ env.FUNCTION_NAME }}"
        echo "Project: ${{ vars.GOOGLE_CLOUD_PROJECT }}"
        
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --gen2 \
          --runtime ${{ env.RUNTIME }} \
          --region ${{ vars.GOOGLE_CLOUD_LOCATION }} \
          --source . \
          --entry-point check_new_analyses \
          --trigger-topic new-analysis-checker-trigger \
          --memory 1GiB \
          --timeout 540s \
          --max-instances 1 \
          --set-env-vars="LANGUAGES=${{ vars.LANGUAGES }},GCP_PROJECT=${{ vars.GOOGLE_CLOUD_PROJECT }},EMAIL_PUBSUB_TOPIC=email-analysis-requests,ANALYSIS_BATCH_SIZE=50,LOOKBACK_HOURS=24" \
          --no-allow-unauthenticated
