name: Deploy Hourly Analysis Checker

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'test'
        type: choice
        options:
        - test
        - prod
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
  push:
    branches:
      - main
    paths:
      - 'hourly_analysis_checker/**'

env:
  FUNCTION_NAME: hourly-analysis-checker
  REGION: ${{ env.GOOGLE_CLOUD_LOCATION }}
  RUNTIME: python311

jobs:
  deploy:
    name: Deploy Hourly Checker
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || inputs.environment || 'test' }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.GOOGLE_CLOUD_PROJECT }}

    - name: Create Pub/Sub topics
      run: |
        echo "📋 Creating Pub/Sub topics..."
        
        # Create hourly-checker-trigger topic
        echo "Creating hourly-checker-trigger topic..."
        if gcloud pubsub topics describe hourly-checker-trigger --project=${{ env.GOOGLE_CLOUD_PROJECT }} &>/dev/null; then
          echo "✅ Topic hourly-checker-trigger already exists"
        else
          gcloud pubsub topics create hourly-checker-trigger --project=${{ env.GOOGLE_CLOUD_PROJECT }} || {
            echo "❌ Failed to create hourly-checker-trigger topic"
            exit 1
          }
          echo "✅ Created topic: hourly-checker-trigger"
        fi

    - name: Deploy Cloud Function
      run: |
        cd hourly_analysis_checker
        
        echo "🚀 Deploying Hourly Analysis Checker..."
        echo "Function name: ${{ env.FUNCTION_NAME }}"
        echo "Project: ${{ env.GOOGLE_CLOUD_PROJECT }}"
        
        gcloud functions deploy ${{ env.FUNCTION_NAME }} \
          --gen2 \
          --runtime ${{ env.RUNTIME }} \
          --region ${{ env.REGION }} \
          --source . \
          --entry-point check_new_analyses \
          --trigger-topic hourly-checker-trigger \
          --memory 1GiB \
          --timeout 540s \
          --max-instances 1 \
          --set-env-vars="GCP_PROJECT=${{ env.GOOGLE_CLOUD_PROJECT }},EMAIL_PUBSUB_TOPIC=hourly-checker-trigger,ANALYSIS_BATCH_SIZE=50,LOOKBACK_HOURS=1" \
          --no-allow-unauthenticated
